spring: 
  profiles: 
    active: dev
  jpa: 
    database : MYSQL  
    show-sql : true  
    hibernate:  
      ddl-auto : update 
  mail: 
    host: smtp.qq.com
    username: leealigner@qq.com
    password: *****************
    properties: 
      mail:
        smtp: 
          auth: true
          starttls:
            enable: true
            required: true
    
