server:
  context-path: /aligner
  port: 2080
spring: 
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ealignerdb?useUnicode=true&characterEncoding=utf8
    username: root
    password: eAligner!1
