server:
  context-path: /aligner
  port: 3080
  
spring: 
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.18.201.46:3306/ealignerdb?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123asd!@#
